# Generated by Django 5.1 on 2024-09-07 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('category_id', models.IntegerField(choices=[(1, 'Sales And Marketing'), (2, 'Web And Programming And Software'), (3, 'Finance And Accounting'), (4, 'Executive And Administrative Office Manager'), (5, 'Digital Marketing'), (6, 'Content Production And Management'), (7, 'Support And Finance'), (8, 'It Devops Server'), (9, 'Design'), (10, 'Industrial Engineering And Industrial Management'), (11, 'Education'), (12, 'Simple Worker And Service Force'), (13, 'Shopping And Business'), (14, 'Electrical And Electronic Engineering'), (15, 'Human Resources And Recruitment'), (16, 'Civil Engineering And Architecture'), (17, 'The Field Of Cinema And Image'), (18, 'Warehousing'), (19, 'Technical Technician And Repairman'), (20, 'Tourism'), (21, 'Mechanical And Aerospace Engineering'), (22, 'Product Manager'), (23, 'Market Research And Economic Analysis'), (24, 'Medicine Nursing And Medicine'), (25, 'Transportation'), (26, 'Research And Development'), (27, 'Food Industry'), (28, 'Skilled Laborer And Industrial Worker'), (29, 'Hotel Management'), (30, 'Legal Expert And Lawyer'), (31, 'Car And Motor Courier'), (32, 'Public Relations'), (33, 'Insurance Management'), (34, 'Guard'), (35, 'Chemical And Petroleum Engineering'), (36, 'Translation'), (37, 'Hse'), (38, 'Mining And Metallurgy Engineering'), (39, 'Textile Engineering And Fabric And Clothing Design'), (40, 'Chemistry And Pharmaceuticals'), (41, 'Medical Engineering'), (42, 'Biological And Laboratory Sciences'), (43, 'Journalist'), (44, 'Agricultural Engineering'), (45, 'Polymer Engineering'), (46, 'Physical Education'), (47, 'Ceo'), (48, 'Music And Sound')], null=True)),
                ('place_type_id', models.IntegerField(choices=[(1, 'In Person'), (2, 'Remote'), (3, 'Semi Attendance')], null=True)),
                ('employment_type_id', models.IntegerField(choices=[(1, 'Full Time'), (2, 'Part Time'), (3, 'Contractual')], null=True)),
                ('seniority_id', models.IntegerField(choices=[(1, 'Employee'), (2, 'Expert'), (3, 'Senior'), (4, 'Middle Manager'), (5, 'Top Manager')], null=True)),
                ('gender_id', models.IntegerField(choices=[(1, 'Man'), (2, 'Woman'), (3, 'Not Important')], null=True)),
                ('military_status_id', models.IntegerField(choices=[(1, 'Not Important'), (2, 'Finished Or Permanent Exemption'), (3, 'Educational Exemption')], null=True)),
                ('status_id', models.IntegerField(choices=[(1, 'Alive'), (2, 'Expired')], null=True)),
                ('salary_type_id', models.IntegerField(choices=[(1, 'Agreed'), (2, 'Hourly'), (3, 'Daily'), (4, 'Weekly'), (5, 'Monthly'), (6, 'Yearly')], null=True)),
                ('is_intern', models.BooleanField(blank=True, null=True)),
                ('min_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('min_salary', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000000000)])),
                ('max_salary', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000000000)])),
                ('min_work_experience', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_work_experience', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('public_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
