# Generated by Django 5.1 on 2024-10-06 09:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('industry_id', models.IntegerField(choices=[(1, 'Computer And Information Technology And Internet'), (2, 'Production And Industries'), (3, 'Advertising And Recovery And Branding'), (4, 'Medical And Health Services'), (5, 'Architecture And Civil Engineering'), (6, 'Education And Schools And Universities'), (7, 'Media And Publications'), (8, 'Oil And Gas'), (9, 'Tourism And Hotel'), (10, 'Financial And Credit'), (11, 'Telecom'), (12, 'Real Estate'), (13, 'Insurance'), (14, 'Human Resources'), (15, 'Force'), (16, 'Advocacy And Legal'), (17, 'Government'), (18, 'Other')], null=True)),
                ('title', models.TextField()),
                ('min_employees', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)])),
                ('max_employees', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)])),
                ('built_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1100), django.core.validators.MaxValueValidator(1403)])),
                ('website', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('public_address', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=1000, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=None, max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camp.companypage'),
        ),
    ]
